name: Lint Helm charts 

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.3.0
      - name: Lint charts
        run: |
            for dir in $(find . -type d -mindepth 1 -maxdepth 1); do
              if [[ -f "${dir}/Chart.yaml" ]]; then
                CHARTS+=("${dir}")
                echo "Found chart directory ${dir}"
              else
                echo "Ignoring non-chart directory ${dir}"
              fi
            done

            for chart in ${CHARTS[@]}; do
              helm dependency update "${chart}"
            done

            helm lint ${CHARTS[*]}
